source /etc/profile.d/qt6.rc  &&

OPTS+=" -DMOD_GLAXNIMATE=OFF \
        -DMOD_GLAXNIMATE_QT6=OFF \
        -DMOD_QT=OFF \
        -DMOD_SDL1=OFF \
        -DMOD_QT6=ON \
        -DSWIG_PYTHON=ON"

default_cmake_build
