source /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

# Boolean values required, mostly.
OPTS+=" -DUSE_SYSTEM_LIBS=1 -DSYSTEM_LIBS_REQUIRED=1 -DINSTALL_HICOLOR_ICONS=1 -DDISABLE_UPDATE_CHECK=1"

default_cmake_build
