source /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

#This is needed for now.
source /etc/profile.d/qt5.rc &&

OPTS+=" -DBUILD_WITH_QT6=ON -DBUILD_DESKTOPTHEMES=ON -DKDE_INSTALL_USE_QT_SYS_PATHS=ON"

default_cmake_build
