
  . /etc/profile.d/qt5.rc &&

#  sedit 's:add_subdirectory(qpa)::' plugins/CMakeLists.txt &&

  OPTS+=" -DCMAKE_INSTALL_LIBEXECDIR=lib" &&
#  OPTS+=" -DKDE_INSTALL_USE_QT_SYS_PATHS=1" &&

  default_cmake_build
