. /etc/profile.d/qt5.rc &&

#OPTS+=" -DSHARE_INSTALL_DIR=/usr/share -DBUILD_DOXYGEN_DOCS=OFF -DBUILD_WITH_WEBENGINE=OFF" &&
OPTS+=" -DSHARE_INSTALL_DIR=/usr/share" &&

Qt5_DIR=/usr/lib/qt5 &&

default_cmake_build
