
  sedit '29i #include <exiv2/exiv2.hpp>' src/TransplantExif/TransplantExifDialog.cpp &&
  sedit '37i #include <exiv2/exiv2.hpp>' src/Exif/ExifOperations.cpp &&
  . /etc/profile.d/qt5.rc &&

  default_cmake_build
