source /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

OPTS+=" -DBUILD_WITH_QT6=ON \
        -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
        -DKDE_INSTALL_INCLUDEDIR=include \
        -DKDE_INSTALL_BINDIR=bin \
        -DKDE_INSTALL_LIBDIR=lib"

default_cmake_build
