  . /etc/profile.d/qt6.rc &&


  OPTS+=" -DBUILD_TESTS=0 \
          -DQT6=ON \
          -DQCA_INSTALL_IN_QT_PREFIX=ON \
          -DQCA_FEATURE_INSTALL_DIR=/usr/lib/qt6/mkspec/features \
          -DQCA_PLUGINS_INSTALL_DIR=/usr/lib/qt6/plugins" &&

  default_cmake_build
