. /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

OPTS+=" -DQT6=ON \
        -DBUILD_WITH_QT6=ON \
        -DBUILD_TOOLS=ON \
        -DQCA_FEATURE_INSTALL_DIR=/usr/lib/qt6/mkspecs/features \
        -DQCA_PLUGINS_INSTALL_DIR=/usr/lib/qt6/plugins"

default_cmake_build
