
  
  OPTS+=" -DENABLE_DBUS=1       \
          -DENABLE_INOTIFY=1    \
          -DENABLE_FAM=1        \
          -DENABLE_CLUCENE=0    \
          -DENABLE_CLUCENE_NG=0 \
          -DENABLE_FFMPEG=0     \
          -DENABLE_QT4=1"       &&

  default_cmake_build
