
  OPTS+=" -DENABLE_DBUS=1       \
          -DENABLE_INOTIFY=1    \
          -DENABLE_FAM=1        \
          -DENABLE_CLUCENE=1    \
          -DENABLE_CLUCENE_NG=1 \
          -DENABLE_FFMPEG=1     \
          -DENABLE_QT4=1"       &&

  default_cmake_build
