source /etc/profile.d/qt5.rc &&

OPTS+=" -DWITH_TESTS=OFF \
        -DKEEPASSXC_BUILD_TYPE=Release \
        -DWITH_APP_BUNDLE=OFF \
        -DWITH_XC_ALL=ON \
        -DWITH_XC_DOCS=OFF \
        -DWITH_XC_SSHAGENT=ON \
        -DWITH_XC_YUBIKEY=ON \
        -DWITH_XC_UPDATECHECK=OFF"

default_cmake_build
