. /etc/profile.d/qt6.rc  &&

OPTS+=" -DCMAKE_CXX_STANDARD=17 -DQT_VERSION=6"

default_cmake_build &&

#ln -sf /usr/lib64/ShowMySky-Qt6 /usr/lib64/ShowMySky &&
ln -sf /usr/lib64/ShowMySky-Qt6/cmake/ShowMySky-Qt6Config.cmake /usr/lib64/ShowMySky-Qt6/cmake/ShowMySkyConfig.cmake &&
ln -sf /usr/lib64/ShowMySky-Qt6/cmake/ShowMySky-Qt6Config-release.cmake /usr/lib64/ShowMySky-Qt6/cmake/ShowMySkyConfig-release.cmake
