source /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

OPTS+=" -DQt6WebEngineWidgets_DIR=/usr/qt6/cmake/Qt6WebEngineWidgets/ \
        -DQt6Xml_DIR=/usr/lib/qt6/cmake/Qt6Xml"

default_cmake_build
