
  . /etc/profile.d/qt5.rc &&

  export ac_qmake=/usr/lib/qt5/bin/qmake \
         ac_moc=/usr/lib/qt5/bin/moc \
         ac_uic=/usr/lib/qt5/bin/uic \
         ac_lupdate=/usr/lib/qt5/bin/lupdate \
         ac_lrelease=/usr/lib/qt5/bin/lrelease \
         QMAKE=/usr/lib/qt5/bin/qmake &&

  default_build
