source /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

OPTS+=" -DWITH_NEW_POWER_ASYNC_API=ON \
        -DWITH_NEW_POWER_ASYNC_FREEDESKTOP=ON \
        -DWITH_NEW_SOLID_JOB=ON \
        -DKDE_INSTALL_USE_QT_SYS_PATHS=ON"

default_cmake_build
