 . /etc/profile.d/qt4.rc &&
 . /etc/profile.d/kde4.rc &&

# To avoid conflicts with baloo-frameworks
 OPTS+=" -DCMAKE_INSTALL_PREFIX=/usr/lib/baloo -DAkonadi_DIR=/usr/lib/akonadi4/lib/cmake/Akonadi" &&

 default_cmake_build
