
  . /etc/profile.d/qt5.rc &&

  OPTS+=" -DDocBookXSL_DIR=/usr/share/sgml/docbook/xsl-stylesheets-`lvu version docbook-xsl` \
          -DDocBookXML4_DTD_DIR=/usr/share/sgml/docbook/xml/4.5" &&
  
  default_cmake_build
