
  . /etc/profile.d/qt5.rc &&

  OPTS+=" -DKDE_INSTALL_USE_QT_SYS_PATHS=1   \
          -DCMAKE_DISABLE_FIND_PACKAGE_FontNotoSans=true \
          -DCMAKE_DISABLE_FIND_PACKAGE_FontHack=true" &&

  default_cmake_build
