  sedit 's:gst_caps_append(object<GstCaps>(), gst_caps_copy(caps2));:const GstCaps * caps2ptr = caps2; \gst_caps_append(object<GstCaps>(), gst_caps_copy(caps2ptr));:' src/QGst/caps.cpp &&

  . /etc/profile.d/qt5.rc &&

  OPTS+=" -DQT_VERSION=5 -DQTGSTREAMER_EXAMPLES=0 -DQTGSTREAMER_STATIC=0 -DQTGSTREAMER_CODEGEN=1" &&

  default_cmake_build
