. /etc/profile.d/qt6.rc &&
export LANG='en_US.UTF-8'

OPTS=" -D CMAKE_INSTALL_PREFIX=/usr \
       -D CMAKE_INSTALL_LIBDIR=lib  \
       -D CMAKE_BUILD_TYPE=Release  \
       -D BUILD_WITH_QT6=ON"

default_cmake_build
