source /etc/profile.d/qt6.rc &&

OPTS+=" -DCMAKE_INSTALL_LIBEXECDIR=lib \
        -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
        -DQt6QmlCompilerPlusPrivate_DIR=/usr/lib/qt6/cmake/Qt6QmlCompiler"

default_cmake_build
