
  source /etc/profile.d/qt4.rc &&
  source /etc/profile.d/kde4.rc &&

# Prefer it look here instead of /usr/lib/mozilla/plugins
  OPTS+=" -DMOZPLUGIN_INSTALL_DIR=/usr/lib/lunar/plugins" &&

  default_cmake_build
